services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: kex-server
    ports:
      - "8443:8443"
    volumes:
      - ./logs:/app/logs
      - ./shared/config.json:/app/config.json
    networks:
      - kex-net

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: kex-client
    depends_on:
      - server
    volumes:
      - ./logs:/app/logs
      - ./shared/config.json:/app/config.json
    networks:
      - kex-net

networks:
  kex-net:
    driver: bridge