services:
  client:
    container_name: "client"
    build:
      context: ./docker/clientserver
      args:
        OPENSSL_REPO: "https://github.com/tumi8/openssl-pqc.git"
        OPENSSL_BRANCH: "basic-sphincs-psh"
        LIBOQS_COMMIT: "2e2ddb4e0493014694820471396984b30d59cf97"
        CPU_PROFILING: "${CPU_PROFILING}"
    privileged: true
    entrypoint: /opt/measurement-openssl-client.sh
    environment:
      - KEM_ALG=${KEM_ALG}
      - SIG_ALG=${SIG_ALG}
      - MEASUREMENT_TIME=60
      - CPU_PROFILING=${CPU_PROFILING}
      - NETEM_TC=${NETEM_TC}
    volumes:
      - cert-data:/opt/shared
      - type: bind
        source: ${HOST_DIR}/client
        target: /out
      - type: bind
        source: ./shared
        target: /opt/shared

  server:
    container_name: "server"
    build:
      context: ./docker/clientserver
      args:
        OPENSSL_REPO: "https://github.com/tumi8/openssl-pqc.git"
        OPENSSL_BRANCH: "basic-sphincs-psh"
        LIBOQS_COMMIT: "2e2ddb4e0493014694820471396984b30d59cf97"
        CPU_PROFILING: "${CPU_PROFILING}"
    privileged: true
    entrypoint: /opt/measurement-openssl-server.sh
    environment:
      - KEM_ALG=${KEM_ALG}
      - SIG_ALG=${SIG_ALG}
      - CPU_PROFILING=${CPU_PROFILING}
      - NETEM_TC=${NETEM_TC}
    volumes:
      - cert-data:/opt/shared
      - type: bind
        source: ${HOST_DIR}/server
        target: /out
      - type: bind
        source: ./shared
        target: /opt/shared

volumes:
  cert-data:
